# In _config.yml
title: Ligo and Leif Cooperative Research Project for Make Benefit Glorious Nation of Norway.
author: Ligo Scientific Collaboration (LSC) and Leif-Martin Sæther Sunde
logo: logo.png
execute:
  execute_notebooks: force

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib