name: ligo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=2.7
  - decorator=4.4
  - ipykernel=4.8
  - numpy=1.16
  - scipy=1.2
  - matplotlib=2.2
  - h5py=2.10
  - pip
#  - pip:
  # works for regular pip packages
#    - .=0.0.1
#    - pytest=4.6